### ISSUE TITLE
Can't find Scope implementation when using ScopeFactory

### ISSUE THREAD

**Issue by mcassiano** [uber/motif#188]
**Library version**: 0.3.1

**Repro steps or stacktrace**: There are no clear repro steps, but building with Gradle from Android Studio will break sometimes.

```
2020-02-12 21:59:05.498 7216-7216/redacted E/AndroidRuntime: FATAL EXCEPTION: main
    Process: redacted, PID: 7216
    java.lang.RuntimeException: Unable to create application redacted.App: java.lang.RuntimeException: Could not find Scope implementation class redacted.AppScopeFactoryImpl. Ensure that the Motif annotation processor is enabled and that proguard is configured correctly (See README for details).
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.RuntimeException: Could not find Scope implementation class redacted.AppScopeFactoryImpl. Ensure that the Motif annotation processor is enabled and that proguard is configured correctly (See README for details).
        at motif.ScopeFactory.getScopeImplClass(ScopeFactory.java:70)
        at motif.ScopeFactory.getConstructor(ScopeFactory.java:58)
        at motif.ScopeFactory.create(ScopeFactory.java:39)
        at motif.ScopeFactory.create(ScopeFactory.java:35)
        at redacted.App.onCreate(App.kt:20)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Leland-Takamine** [comment]
Thanks for the report - I'll keep an eye out for this. Let me know if you find a repro case.

**Comment by mcassiano** [comment]
It's also breaking builds over `ScopeImpl`s not being found. I think it has to do with lack of support for incremental annotation processing (#34).
