### ISSUE TITLE
IntelliJ Plugin Crash

### ISSUE THREAD

**Issue by Leland-Takamine** [uber/motif#189]
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'root' of com/intellij/ide/util/treeView/TreeBuilderUtil.storePaths must not be null
	at com.intellij.ide.util.treeView.TreeBuilderUtil.$$$reportNull$$$0(TreeBuilderUtil.java)
	at com.intellij.ide.util.treeView.TreeBuilderUtil.storePaths(TreeBuilderUtil.java)
	at com.intellij.ide.hierarchy.HierarchyBrowserBaseEx.doRefresh(HierarchyBrowserBaseEx.java:551)
	at motif.intellij.hierarchy.ScopePropertyHierarchyBrowser.access$doRefresh(ScopePropertyHierarchyBrowser.kt:52)
	at motif.intellij.hierarchy.ScopePropertyHierarchyBrowser$setSelectedScope$1.run(ScopePropertyHierarchyBrowser.kt:78)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93
```

**Comment by oliviernotteghem** [comment]
This should be fixed in latest version of plugin.
